"""Optional high-level work identities and structural commands."""

from .model import (
    GraphCycleError,
    InvalidDependencyError,
    InvalidParentError,
    Lifecycle,
    WorkError,
    WorkKind,
    WorkNotFoundError,
    WorkRecord,
    WorkStateView,
    WorkValidationError,
)
from .module import (
    DEFAULT_TITLE,
    DOMAIN_ID,
    DOMAIN_OWNER,
    DOMAIN_VERSION,
    SCHEMA_REVISION,
    WorkGraph,
    WorkModule,
    WorkStore,
    contribution,
    contributions,
    register_work,
    work_handler,
)
from .lifecycle import (
    LIFECYCLE_DOMAIN_ID,
    LIFECYCLE_EVENT,
    LIFECYCLE_OPERATION,
    LIFECYCLE_SCHEMA_REVISION,
    ProjectLifecycle,
    ProjectLifecycleError,
)
from .orchestration import (
    DEFAULT_KIND,
    ORCHESTRATION_DOMAIN_ID,
    ORCHESTRATION_SCHEMA_REVISION,
    Orchestration,
)

__all__ = [
    "DEFAULT_TITLE",
    "DOMAIN_ID",
    "DOMAIN_OWNER",
    "DOMAIN_VERSION",
    "GraphCycleError",
    "InvalidDependencyError",
    "InvalidParentError",
    "LIFECYCLE_DOMAIN_ID",
    "LIFECYCLE_EVENT",
    "LIFECYCLE_OPERATION",
    "LIFECYCLE_SCHEMA_REVISION",
    "Lifecycle",
    "SCHEMA_REVISION",
    "WorkError",
    "WorkGraph",
    "WorkKind",
    "WorkModule",
    "WorkNotFoundError",
    "WorkRecord",
    "WorkStateView",
    "WorkStore",
    "WorkValidationError",
    "ProjectLifecycle",
    "ProjectLifecycleError",
    "contribution",
    "contributions",
    "register_work",
    "work_handler",
    "DEFAULT_KIND",
    "ORCHESTRATION_DOMAIN_ID",
    "ORCHESTRATION_SCHEMA_REVISION",
    "Orchestration",
]
